live_config_reload = true

import = [
  "~/.config/alacritty/tokyo-night.toml"
]

shell = { program = "zsh", args = ["-l", "-c", "tmux a -t base || tmux new -s base"] }

[font]
size = 12

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Italic_Bold"

[scrolling]
history = 1000

[window]
padding = { x = 5, y = 5 }
# decorations = "none"
decorations_theme_variant = "dark"
startup_mode = "Fullscreen"
# startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Off" }

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
]
