live_config_reload = true

import = [
  "~/.config/alacritty/tokyo-night.toml"
]

shell = { program = "zsh", args = ["-l", "-c", "tmux a -t base || tmux new -s base"] }

[font]
size = 10

[font.bold]
family = "FiraMonoNerdFont"
style = "bold"

[font.italic]
family = "FiraMonoNerdFont"
style = "italic"

[font.normal]
family = "FiraMonoNerdFont"
style = "regular"

[scrolling]
history = 1000

[window]
padding = { x = 5, y = 5 }
decorations = "none"
decorations_theme_variant = "dark"
startup_mode = "Fullscreen"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

