
# If uncommented, this will be used as startup command, creating a new tmux session or attaching to an existing one
# It will not allow to detach from the session, so the terminal will close when the tmux session is closed
# shell = { program = "zsh", args = ["-l", "-c", "tmux a -t base || tmux new -s base"] }

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.normal]
# family = "FiraCode Nerd Font"
family = "Terminess Nerd Font"
style = "Regular"

[font.bold]
# family = "FiraCode Nerd Font"
family = "Terminess Nerd Font"
style = "Bold"

[font.italic]
# family = "FiraCode Nerd Font"
family = "Terminess Nerd Font"
style = "Italic"

[font.bold_italic]
# family = "FiraCode Nerd Font"
family = "Terminess Nerd Font"
style = "Italic_Bold"

[scrolling]
history = 1000

[window]
opacity = 0.8
blur = true
padding = { x = 5, y = 5 }
decorations = "Buttonless"
decorations_theme_variant = "Dark"
# startup_mode = "Fullscreen"
startup_mode = "Maximized"
option_as_alt = "Both"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Off" }

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  { key = "Slash", mods = "Control", chars = "\u001f" },
]

[general]
live_config_reload = true

import = [
  "~/.config/alacritty/tokyo-night.toml"
]
